-- Custom SQL migration file, put your code below! --
-- bm25 indexes skipped: pg_search/ParadeDB not available on Neon free tier
-- Full-text search via bm25 is disabled; standard postgres search still works
